### ISSUE TITLE
add kibana configuration steps in documentation or automatically configure kibana at install time

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#22]
I've added manually "measure" index-pattern in kibana but I can't see any visualization in Platform/Measure collect.

see the image bellow 
<img width="1364" alt="screen shot 2017-09-28 at 13 35 01" src="https://user-images.githubusercontent.com/534538/30962310-f116d390-a451-11e7-8b42-3b9241ac66bc.png">

**Comment by aabherve** [comment]
Kibana index are now managed by the platform

**Comment by NG-GOM** [comment]
Hello,

Is there an official workaround for this problem under MeasurePlatform v0.5.0.2 ?

I've created an index pattern on the Kibana web interface ( Management > Index Patterns > Configure an index pattern) with the following parameters :

|||
| ---------- | ---------- |
| **Index pattern name** | `measure` |
| **Index pattern ID**  | `measure` |
| **Time Filter field name** | `postDate` |

It barely seemed to fix the problem on the "Measure collect" page (no more errors but a malformed graph, I admitted the bad display is due to an old version of Mozilla Firefox), but a an error is encountered after adding a new visualization on the project's page. The error message says : "Could not locate that index-pattern-field (id: value)".
I guess both problems are due to a non-initialization of Kibana indexes, but i don't figure out how to fix this problem while staying with the v0.5.0.2, and I'd like to avoid changing the version of the software in the middle of a test run.

Please find attached :
- A screenshot of the malformed graph : ![malformed_graph](https://user-images.githubusercontent.com/33718939/32896336-11c3afe8-cae3-11e7-9b6c-c6d2b7259f75.png)
- A screenshot of the "index-pattern-field" error from the Project page : ![page_projetng-pb_index-pattern-field](https://user-images.githubusercontent.com/33718939/32896446-4f2601e2-cae3-11e7-923b-64378188b4b4.png)


Thank you,
Best Regards,
NG/GOM

*__Configuration :__*

|||
| - | - |
**OS** | Linux CentOS 6.5
**Kernel** | 2.6.32-431.el6.x86_64
**Elasticsearch** | v5.6.0
**Kibana** | v5.6.0
**MeasurePlatform** | v0.5.0.2
**Mozilla Firefox** | v17.0.10
