### ISSUE TITLE
MMT measure maven compilation, to generate jar [Evaluation Scenario 3] 

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#29]
Measure MMT packages do not compile with error 

>  Could not resolve dependencies for project org.measure:MEASURE-MMTAppResponseTimePlugin:jar:0.1-SNAPSHOT: Failure to find org.measure.smmmeasure.api:SMMMeasureApi:jar:0.5.00

**Comment by dieriver** [comment]
The project implements the SMM API, which is a dependency of any MMT plugin. In order to correctly compile the plugin, it is required to download the API (https://github.com/ITEA3-Measure/SMMMeasureApi), compile it and then compile the MMT plugin.

We will update the wiki pages to reflect this requirement ¡,

**Comment by Prasoonda** [comment]
Thanks, it works now.

Thank you for updating it in wiki for other evaluators.
